import { globalStyle, style } from "@vanilla-extract/css";

export const appRoot = style({ display: "grid", gridTemplateColumns: "220px minmax(0, 1fr)", width: "100vw", height: "100vh", overflow: "hidden", background: "var(--app-background)", selectors: { "&[data-sidebar-mode=collapsed]": { gridTemplateColumns: "68px minmax(0, 1fr)" } } });
export const sidebar = style({ display: "flex", flexDirection: "column", minWidth: 0, padding: "24px 14px", borderRight: "1px solid var(--border-subtle)", background: "var(--sidebar-background)", transition: "width 160ms ease, padding 160ms ease" });
export const brand = style({ padding: "0 12px 28px", fontWeight: 750, letterSpacing: "-0.02em", color: "var(--text-primary)" });
export const navGroup = style({ display: "grid", gap: 5 });
export const navButton = style({ display: "flex", alignItems: "center", gap: 12, minHeight: 42, width: "100%", padding: "8px 11px", border: 0, borderRadius: 10, background: "transparent", color: "var(--text-muted)", textAlign: "left", cursor: "pointer", selectors: { "&[aria-current=page]": { background: "var(--active-background)", color: "var(--text-primary)", fontWeight: 700 }, "&:hover": { background: "var(--active-background)" }, "&:focus-visible": { outline: "3px solid var(--focus-ring)", outlineOffset: 2 } } });
export const navIcon = style({ display: "grid", placeItems: "center", width: 24, height: 24, borderRadius: 7, fontSize: 12, fontWeight: 800, background: "var(--icon-background)" });
export const navLabel = style({ overflow: "hidden", whiteSpace: "nowrap" });
globalStyle(`${appRoot}[data-sidebar-mode=collapsed] .${navLabel}`, { display: "none" });
globalStyle(`${appRoot}[data-sidebar-mode=collapsed] .${brand}`, { fontSize: 0, paddingInline: 11 });
export const divider = style({ height: 1, margin: "12px 10px", background: "var(--border-subtle)" });
export const collapseButton = style({ marginTop: "auto", display: "flex", gap: 12, alignItems: "center", minHeight: 42, padding: "8px 11px", border: 0, borderRadius: 10, background: "transparent", color: "var(--text-muted)", cursor: "pointer" });
export const viewport = style({ minWidth: 0, minHeight: 0, overflow: "auto", padding: "clamp(24px, 5vw, 64px)" });
export const destination = style({ width: "min(900px, 100%)", margin: "0 auto", paddingBottom: 64 });
export const heading = style({ margin: "0 0 10px", color: "var(--text-primary)", fontSize: "clamp(1.8rem, 3vw, 2.5rem)", letterSpacing: "-0.04em" });
export const lede = style({ margin: "0 0 28px", color: "var(--text-muted)", fontSize: "1.05rem" });
export const placeholder = style({ minHeight: 220, display: "grid", placeItems: "center", padding: 32, border: "1px dashed var(--border-subtle)", borderRadius: 16, color: "var(--text-muted)", background: "var(--surface)" });
export const foundationPanel = style({ padding: "24px 0" });
export const coreStatus = style({ color: "var(--text-muted)" });
export const dialogBackdrop = style({ position: "fixed", inset: 0, display: "grid", placeItems: "center", padding: 24, background: "rgba(0,0,0,0.55)", zIndex: 40 });
export const dialogCard = style({ width: "min(520px, 100%)", maxHeight: "80vh", overflow: "auto", padding: 24, borderRadius: 16, border: "1px solid var(--border-subtle)", background: "var(--surface)", color: "var(--text-primary)" });
export const shortcutList = style({ display: "grid", gridTemplateColumns: "1fr auto", gap: "10px 16px", margin: "20px 0 24px", alignItems: "center" });
globalStyle(`${shortcutList} dd`, { margin: 0, justifySelf: "end" });
export const shortcutChord = style({ padding: "3px 9px", borderRadius: 7, border: "1px solid var(--border-subtle)", background: "var(--icon-background)", fontFamily: "inherit", fontSize: "0.9rem", fontWeight: 700, whiteSpace: "nowrap" });
export const dialogButton = style({ minHeight: 38, padding: "8px 16px", borderRadius: 10, border: "1px solid var(--border-subtle)", background: "transparent", color: "var(--text-primary)", cursor: "pointer", selectors: { "&:focus-visible": { outline: "3px solid var(--focus-ring)", outlineOffset: 2 } } });
