import { style } from "@vanilla-extract/css";

export const screen = style({ padding: "28px", maxWidth: "1440px", margin: "0 auto" });
export const header = style({ display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: "24px", marginBottom: "18px", flexWrap: "wrap" });
export const heading = style({ margin: 0, fontSize: "2rem" });
export const lede = style({ margin: "6px 0 0", color: "var(--text-muted, #666)" });
export const createForm = style({ display: "flex", gap: "8px", minWidth: "320px" });
export const portfolios = style({ display: "flex", gap: "6px", flexWrap: "wrap", marginBottom: "16px" });
export const tab = style({ minHeight: "40px", padding: "8px 12px", border: "1px solid var(--border-subtle)", borderRadius: "8px", background: "var(--surface)", color: "inherit", cursor: "pointer", selectors: { '&[aria-selected="true"], &[aria-pressed="true"]': { outline: "2px solid var(--accent)", outlineOffset: "1px" }, "&:disabled": { opacity: 0.5, cursor: "not-allowed" } } });
export const workspace = style({ display: "grid", gridTemplateColumns: "minmax(240px, 320px) minmax(0, 1fr)", gap: "18px", alignItems: "start", '@media': { '(max-width: 860px)': { gridTemplateColumns: "1fr" } } });
export const listPanel = style({ border: "1px solid var(--border-subtle)", borderRadius: "12px", padding: "10px", background: "var(--surface)", maxHeight: "calc(100vh - 220px)", overflowY: "auto" });
export const planList = style({ listStyle: "none", padding: 0, margin: 0, display: "grid", gap: "8px" });
export const planButton = style({ width: "100%", display: "grid", gap: "4px", textAlign: "left", padding: "12px", border: "1px solid var(--border-subtle)", borderRadius: "9px", background: "transparent", color: "inherit", cursor: "pointer", selectors: { '&[aria-current="true"]': { borderColor: "var(--accent)", background: "color-mix(in srgb, var(--accent) 8%, transparent)" } } });
export const detailPanel = style({ border: "1px solid var(--border-subtle)", borderRadius: "12px", padding: "20px", background: "var(--surface)", minHeight: "420px" });
export const detailHeader = style({ display: "flex", justifyContent: "space-between", gap: "16px", alignItems: "flex-start", marginBottom: "16px" });
export const fieldset = style({ display: "grid", gap: "12px", border: "1px solid var(--border-subtle)", borderRadius: "10px", padding: "16px", margin: "0 0 22px" });
export const tagFieldset = style({ display: "flex", flexWrap: "wrap", gap: "10px", border: 0, padding: 0, margin: 0 });
export const checkLabel = style({ display: "inline-flex", gap: "6px", alignItems: "center" });
export const twoColumns = style({ display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: "12px", '@media': { '(max-width: 700px)': { gridTemplateColumns: "1fr" } } });
export const input = style({ width: "100%", boxSizing: "border-box", minHeight: "40px", padding: "8px 10px", border: "1px solid var(--border-subtle)", borderRadius: "8px", background: "var(--surface)", color: "inherit", font: "inherit" });
export const textarea = style([input, { minHeight: "94px", resize: "vertical" }]);
export const primaryButton = style({ minHeight: "40px", padding: "8px 14px", border: 0, borderRadius: "8px", background: "var(--accent)", color: "#fff", fontWeight: 700, cursor: "pointer", selectors: { "&:disabled": { opacity: 0.5, cursor: "not-allowed" } } });
export const secondaryButton = style({ minHeight: "36px", padding: "6px 10px", border: "1px solid var(--border-subtle)", borderRadius: "8px", background: "transparent", color: "inherit", cursor: "pointer", selectors: { "&:disabled": { opacity: 0.5, cursor: "not-allowed" } } });
export const dangerButton = style([secondaryButton, { color: "var(--error, #b42318)" }]);
export const iconButton = style([secondaryButton, { minWidth: "36px", padding: "4px" }]);
export const actions = style({ display: "flex", gap: "8px", flexWrap: "wrap" });
export const error = style({ color: "var(--error, #b42318)", padding: "10px 12px", border: "1px solid currentColor", borderRadius: "8px" });
export const muted = style({ color: "var(--text-muted, #666)", fontSize: "0.9rem" });
export const emptyState = style({ color: "var(--text-muted, #666)", textAlign: "center", padding: "80px 20px" });
export const draftNote = style({ color: "var(--text-muted, #666)", fontSize: "0.85rem", margin: 0 });
export const variantTabs = style({ display: "flex", gap: "6px", flexWrap: "wrap", marginBottom: "12px" });
export const variantControl = style({ display: "inline-flex", gap: "3px", alignItems: "center" });
export const variantEditor = style({ display: "grid", gap: "12px", paddingTop: "12px" });
export const inlineForm = style({ display: "flex", gap: "8px", alignItems: "center", margin: "10px 0", flexWrap: "wrap" });
export const phaseList = style({ display: "grid", gap: "8px", paddingLeft: "24px" });
export const phaseRow = style({ display: "grid", gridTemplateColumns: "minmax(160px, 1fr) auto auto auto", gap: "6px", alignItems: "center", '@media': { '(max-width: 650px)': { gridTemplateColumns: "1fr auto auto", selectors: { "& > :last-child": { gridColumn: "1 / -1" } } } } });
export const srOnly = style({ position: "absolute", width: "1px", height: "1px", padding: 0, margin: "-1px", overflow: "hidden", clip: "rect(0, 0, 0, 0)", whiteSpace: "nowrap", border: 0 });
