import * as styles from "./categoryIcons.css";

/**
 * The category mark.
 *
 * This rendered two literal Unicode glyphs — `◉` and `◇` — so the mark carried the document font's
 * weight, baseline and metrics rather than the icon vocabulary's, and changed shape with the type
 * system. ADR 0045 §7 rules that out: an icon is a drawing, not a character.
 *
 * The two shapes are kept, because they are a real semantic distinction the Calendar and Analytics
 * surfaces rely on, and are now drawn in CSS at a fixed optical size. That is deliberately not the
 * same as vendoring two more Fluent paths: the icon set is generated by
 * `scripts/generate_visual_icons.py` and adding to it is a separate, reviewable step. This removes
 * the font dependency without pre-empting that decision.
 *
 * `role="img"` because the span carries no text to name itself with — `aria-label` is prohibited on
 * the implicit `generic` role, which the axe contract on the Today row proved.
 */
export function CategoryIcon({ iconKey, label }: { iconKey: string; label: string }) {
  const general = iconKey === "category-general";
  return (
    <span
      role="img"
      aria-label={label}
      data-icon-key={iconKey}
      className={general ? styles.markGeneral : styles.markOther}
    />
  );
}
