import { useEffect,useLayoutEffect,useRef,useState } from "react";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { motion,useReducedMotion } from "motion/react";
import { getLifeBrowseProjection,getPinnedLifeNodes,pinLifeNode,saveLifeNavigationPreference,unpinLifeNode } from "../../ipc/commands";
import type { LifeNodeView } from "../../ipc/generated/LifeNodeView";
import type { PinnedLifeNodeView } from "../../ipc/generated/PinnedLifeNodeView";
import * as styles from "./LifeScreen.css";
import { LifeEditWorkspace } from "./LifeEditWorkspace";
import { BasicLeafReader } from "./document/BasicLeafReader";

type Mode="browse"|"edit"|"pinned"|"reader";
type HistoryEntry={nodeId:string;page:number;mode:"browse"|"pinned";focusId?:string};
type Line={key:string;d:string};
const lifeKeys={browse:(id:string|undefined,page:number)=>["life","browse",id??"remembered",page] as const,pinned:["life","pinned"] as const};

function NodeIcon({iconKey}:{iconKey:string}){return <span className={styles.icon} aria-hidden="true">{iconKey==="life-leaf"||iconKey==="life-note"?"◇":"⌁"}</span>}

function useConnectors(container:React.RefObject<HTMLDivElement|null>,focal:React.RefObject<HTMLDivElement|null>,children:React.RefObject<Map<string,HTMLElement>>){
 const [lines,setLines]=useState<Line[]>([]);
 useLayoutEffect(()=>{const root=container.current;const focus=focal.current;if(!root||!focus)return;const measure=()=>{const base=root.getBoundingClientRect();const top=focus.getBoundingClientRect();setLines(Array.from(children.current.entries()).map(([key,el])=>{const child=el.getBoundingClientRect();const x1=top.left+top.width/2-base.left,y1=top.bottom-base.top,x2=child.left+child.width/2-base.left,y2=child.top-base.top;return{key,d:`M ${x1} ${y1} C ${x1} ${(y1+y2)/2}, ${x2} ${(y1+y2)/2}, ${x2} ${y2}`};}));};measure();const observer=new ResizeObserver(measure);observer.observe(root);observer.observe(focus);children.current.forEach(el=>observer.observe(el));return()=>observer.disconnect();},[container,focal,children]);
 return lines;
}

export function LifeScreen(){
 const client=useQueryClient();const reduced=useReducedMotion();
 const [nodeId,setNodeId]=useState<string>();const [page,setPage]=useState(0);const [mode,setMode]=useState<Mode>("browse");const [initialized,setInitialized]=useState(false);const [history,setHistory]=useState<HistoryEntry[]>([]);const [reader,setReader]=useState<LifeNodeView|PinnedLifeNodeView>();const [busy,setBusy]=useState(false);
 const sceneRef=useRef<HTMLDivElement>(null),focalRef=useRef<HTMLDivElement>(null),childRefs=useRef(new Map<string,HTMLElement>()),restoreFocus=useRef<string|undefined>(undefined);
 const browse=useQuery({queryKey:lifeKeys.browse(nodeId,page),queryFn:()=>getLifeBrowseProjection({node_id:nodeId??null,child_page:page})});
 const pins=useQuery({queryKey:lifeKeys.pinned,queryFn:getPinnedLifeNodes,enabled:mode==="pinned"});
 const lines=useConnectors(sceneRef,focalRef,childRefs);
 useEffect(()=>{if(!browse.data||initialized)return;const preferred=browse.data.preferred_mode as Mode;const safe=preferred==="reader"&&!browse.data.selected.is_leaf?"browse":preferred;setMode(safe);if(preferred==="reader"&&browse.data.selected.is_leaf)setReader(browse.data.selected);setInitialized(true);},[browse.data,initialized]);
 useEffect(()=>{if(!browse.data||!initialized)return;const selected=browse.data.selected.id;saveLifeNavigationPreference({node_id:selected,mode,path_version:1,viewport_anchor:restoreFocus.current??null}).catch(()=>{});},[browse.data,initialized,mode]);
 useEffect(()=>{if(mode==="browse"&&browse.data)requestAnimationFrame(()=>{const target=restoreFocus.current?document.querySelector<HTMLElement>(`[data-life-id="${restoreFocus.current}"]`):document.querySelector<HTMLElement>("[data-life-focal]");target?.focus({preventScroll:true});restoreFocus.current=undefined;});},[browse.data,mode]);
 const pin=useMutation({mutationFn:(value:{id:string;pinned:boolean})=>value.pinned?unpinLifeNode({node_id:value.id}):pinLifeNode({node_id:value.id}),onSuccess:()=>{void client.invalidateQueries({queryKey:["life"]});}});
 const navigate=(node:LifeNodeView|PinnedLifeNodeView,originMode:"browse"|"pinned"=mode==="pinned"?"pinned":"browse")=>{if(busy||("available" in node&&!node.available))return;setBusy(true);const id="id" in node?node.id:node.node_id;if(node.is_leaf){setHistory(v=>[...v,{nodeId:browse.data?.selected.id??id,page,mode:originMode,focusId:id}]);setReader(node);setMode("reader");setBusy(false);return;}setHistory(v=>[...v,{nodeId:browse.data?.selected.id??id,page,mode:originMode,focusId:id}]);setNodeId(id);setPage(0);setMode("browse");setTimeout(()=>setBusy(false),reduced?0:320);};
 const goTo=(id:string)=>{if(browse.data?.selected.id!==id)setHistory(v=>[...v,{nodeId:browse.data?.selected.id??id,page,mode:"browse"}]);setNodeId(id);setPage(0);setMode("browse");};
 const back=()=>{const previous=history.at(-1);if(mode==="reader"){setReader(undefined);}if(previous){setHistory(v=>v.slice(0,-1));restoreFocus.current=previous.focusId;setNodeId(previous.nodeId);setPage(previous.page);setMode(previous.mode);}else if(browse.data?.parent){setNodeId(browse.data.parent.id);setPage(0);setMode("browse");}else setMode("browse");};
 if(browse.isLoading)return <p className={styles.status} aria-live="polite">Loading Life System…</p>;
 if(browse.isError||!browse.data)return <section className={styles.screen}><h1 className={styles.heading}>Life System</h1><p role="alert">Life System could not be loaded. Your tree context is preserved.</p></section>;
 const projection=browse.data;
 if(mode==="reader"&&reader){const readerId="id" in reader?reader.id:reader.node_id;return <section className={styles.reader} aria-labelledby="life-reader-title"><button className={styles.quietButton} onClick={back}>← Back to Life Browse</button><motion.div layoutId={`life-node-${readerId}`} className={styles.readerHero}><NodeIcon iconKey={reader.icon_key}/><h1 id="life-reader-title" className={styles.heading}>{reader.title}</h1><p className={styles.nodeDescription}>{reader.short_description}</p><BasicLeafReader nodeId={readerId}/></motion.div></section>;}
 return <section className={styles.screen} aria-labelledby="life-heading">
  <header className={styles.header}><div><h1 id="life-heading" className={styles.heading} tabIndex={-1}>Life System</h1><p className={styles.nodeDescription}>{mode==="edit"?"Edit the complete structure with atomic moves and undo.":"Browse one branch at a time."}</p></div><div className={styles.modes} aria-label="Life view"><button className={styles.modeButton} aria-pressed={mode==="browse"} onClick={()=>setMode("browse")}>Browse</button><button className={styles.modeButton} aria-pressed={mode==="edit"} onClick={()=>setMode("edit")}>Edit</button><button className={styles.modeButton} aria-pressed={mode==="pinned"} onClick={()=>setMode("pinned")}>Pinned</button></div></header>
  {mode==="edit"?<LifeEditWorkspace initialNodeId={projection.selected.id} onBrowse={id=>{setNodeId(id);setPage(0);setMode("browse");}}/>:mode==="pinned"?<PinnedView items={pins.data??[]} loading={pins.isLoading} onActivate={node=>navigate(node,"pinned")} onUnpin={id=>pin.mutate({id,pinned:true})}/>:<>
   <div className={styles.toolbar}><button className={styles.quietButton} onClick={back} disabled={history.length===0&&!projection.parent}>← Back</button><nav className={styles.breadcrumb} aria-label="Life breadcrumb">{projection.breadcrumb.map((item,index)=><span key={item.id}>{index>0&&<span aria-hidden="true"> / </span>}<button className={styles.crumb} onClick={()=>goTo(item.id)} aria-current={item.id===projection.selected.id?"page":undefined}>{item.title}</button></span>)}</nav></div>
   {projection.resolved_from_fallback&&<p role="status">The remembered location was unavailable, so the nearest available branch was opened.</p>}
   <div className={styles.scene} ref={sceneRef}><svg className={styles.connectors} aria-hidden="true">{lines.map(line=><path key={line.key} d={line.d}/>)}</svg><div className={styles.focalWrap}><motion.div ref={focalRef} layoutId={`life-node-${projection.selected.id}`} className={styles.focal} tabIndex={-1} data-life-focal data-life-id={projection.selected.id}><div className={styles.nodeMeta}><NodeIcon iconKey={projection.selected.icon_key}/><span>{projection.selected.child_count} direct {projection.selected.child_count===1?"child":"children"}</span></div><h2 className={styles.focalTitle}>{projection.selected.title}</h2><p className={styles.nodeDescription}>{projection.selected.short_description}</p><button className={styles.quietButton} onClick={()=>pin.mutate({id:projection.selected.id,pinned:projection.selected.is_pinned})}>{projection.selected.is_pinned?"Unpin focal node":"Pin focal node"}</button></motion.div></div>
    {projection.children.length===0?<div className={styles.empty}><h3>This branch is ready</h3><p>No child nodes have been added yet.</p></div>:<ul className={styles.children} aria-label={`Direct children of ${projection.selected.title}`}>{projection.children.map(child=><li className={styles.childItem} key={child.id} ref={el=>{if(el)childRefs.current.set(child.id,el);else childRefs.current.delete(child.id);}}><motion.button layoutId={`life-node-${child.id}`} className={styles.card} data-life-id={child.id} onClick={()=>navigate(child)} disabled={busy}><NodeIcon iconKey={child.icon_key}/><span className={styles.cardTitle}>{child.title}</span><p className={styles.nodeDescription}>{child.short_description}</p><span className={styles.nodeMeta}>{child.is_leaf?"Leaf — opens Reader":`${child.child_count} direct children`}</span></motion.button><button className={styles.pinButton} aria-label={child.is_pinned?`Unpin ${child.title}`:`Pin ${child.title}`} onClick={()=>pin.mutate({id:child.id,pinned:child.is_pinned})}>{child.is_pinned?"●":"○"}</button></li>)}</ul>}
   </div>{projection.child_page_count>1&&<nav className={styles.paging} aria-label="Child pages"><button className={styles.quietButton} disabled={page===0} onClick={()=>{setNodeId(projection.selected.id);setPage(v=>v-1);}}>Previous children</button><span aria-live="polite">Page {projection.child_page+1} of {projection.child_page_count}</span><button className={styles.quietButton} disabled={page+1>=projection.child_page_count} onClick={()=>{setNodeId(projection.selected.id);setPage(v=>v+1);}}>Next children</button></nav>}</>}
 </section>;
}

function PinnedView({items,loading,onActivate,onUnpin}:{items:PinnedLifeNodeView[];loading:boolean;onActivate:(node:PinnedLifeNodeView)=>void;onUnpin:(id:string)=>void}){if(loading)return <p aria-live="polite">Loading pinned nodes…</p>;if(items.length===0)return <div className={styles.empty}><h2>No pinned nodes</h2><p>Pin a Life node from Browse for quick local access.</p></div>;return <ul className={styles.pinList} aria-label="Pinned Life nodes">{items.map(item=><li className={`${styles.childItem} ${item.available?"":styles.unavailable}`} key={item.node_id}><button className={styles.card} onClick={()=>onActivate(item)} disabled={!item.available}><NodeIcon iconKey={item.icon_key}/><span className={styles.cardTitle}>{item.title}</span><p>{item.available?item.short_description:"Unavailable — this node is archived."}</p><span>{item.available?(item.is_leaf?"Opens Reader":"Opens Browse"):"Unavailable"}</span></button><button className={styles.pinButton} aria-label={`Unpin ${item.title}`} onClick={()=>onUnpin(item.node_id)}>●</button></li>)}</ul>}
