import { fireEvent,render,screen,waitFor,within } from "@testing-library/react";
import { QueryClient,QueryClientProvider } from "@tanstack/react-query";
import { beforeEach,describe,expect,it,vi } from "vitest";
import axe from "axe-core";
import type { LifeEditNodeView } from "../../ipc/generated/LifeEditNodeView";
import type { LifeEditProjection } from "../../ipc/generated/LifeEditProjection";
import { LifeEditWorkspace,buildLifeEditLayout } from "./LifeEditWorkspace";

const api=vi.hoisted(()=>({projection:vi.fn(),create:vi.fn(),rename:vi.fn(),details:vi.fn(),archive:vi.fn(),restore:vi.fn(),reorder:vi.fn(),reparent:vi.fn(),undo:vi.fn()}));
vi.mock("../../ipc/commands",()=>({getLifeEditProjection:api.projection,createLifeNode:api.create,renameLifeNode:api.rename,updateLifeNodeSummary:api.details,archiveLifeNode:api.archive,restoreLifeNode:api.restore,reorderLifeSibling:api.reorder,reparentLifeNode:api.reparent,undoLifeOperation:api.undo}));
const root:LifeEditNodeView={id:"life-root",parent_id:null,title:"Life",short_description:"Root",icon_key:"life-root",theme_variant:"neutral",sort_key:0,depth:0,child_count:2,is_leaf:false,has_document:false,is_pinned:false,revision:0,tags:[]};
const a:LifeEditNodeView={id:"00000000-0000-7000-8000-000000000001",parent_id:"life-root",title:"Branch A",short_description:"A",icon_key:"life-branch",theme_variant:"blue",sort_key:0,depth:1,child_count:1,is_leaf:false,has_document:false,is_pinned:true,revision:0,tags:[]};
const b:LifeEditNodeView={id:"00000000-0000-7000-8000-000000000002",parent_id:"life-root",title:"Branch B",short_description:"B",icon_key:"life-contingency",theme_variant:"green",sort_key:1,depth:1,child_count:0,is_leaf:true,has_document:false,is_pinned:false,revision:0,tags:[]};
const grand:LifeEditNodeView={id:"00000000-0000-7000-8000-000000000003",parent_id:a.id,title:"Grandchild",short_description:"G",icon_key:"life-leaf",theme_variant:"neutral",sort_key:0,depth:2,child_count:0,is_leaf:true,has_document:false,is_pinned:false,revision:0,tags:[]};
const archived:LifeEditNodeView={...grand,id:"00000000-0000-7000-8000-000000000004",title:"Archived",revision:1};
const fixture:LifeEditProjection={root_id:"life-root",tree_revision:4,nodes:[root,a,grand,b],archived_nodes:[archived],latest_undo:"undo-4"};
const result=(node=a)=>({node:{id:node.id,title:node.title,short_description:node.short_description,icon_key:node.icon_key,branch_theme_id:node.theme_variant,child_count:node.child_count,is_leaf:node.is_leaf,is_pinned:node.is_pinned,revision:node.revision+1},tree_revision:5,invalidation:["life-edit"],undo_token:"next"});
const renderEdit=(onBrowse=vi.fn())=>{const client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});return {...render(<QueryClientProvider client={client}><LifeEditWorkspace initialNodeId={a.id} onBrowse={onBrowse}/></QueryClientProvider>),client};};
const selectNode=async(id=a.id)=>{await screen.findByRole("tree",{name:"Full Life tree editor"});fireEvent.click(document.querySelector<HTMLElement>(`[data-life-edit-id="${id}"]`)!);};
const openNodeEditor=async(id=a.id)=>{await selectNode(id);fireEvent.click(screen.getByRole("button",{name:"Edit node"}));};

describe("Life Edit workspace",()=>{
 beforeEach(()=>{api.projection.mockResolvedValue(fixture);for(const mock of [api.create,api.rename,api.details,api.archive,api.restore,api.reorder,api.reparent,api.undo])mock.mockResolvedValue(result());});
 it("renders the complete active tree including grandchildren",async()=>{renderEdit();const tree=await screen.findByRole("tree",{name:"Full Life tree editor"});expect(within(tree).getAllByRole("treeitem")).toHaveLength(4);expect(within(tree).getByText("Grandchild")).toBeInTheDocument();});
 it("uses compact cards without redundant child counts",async()=>{renderEdit();await screen.findByText("Branch A");expect(screen.getByText("Pinned")).toBeInTheDocument();expect(screen.queryByText(/children/)).not.toBeInTheDocument();expect(screen.getAllByText("Leaf").length).toBeGreaterThan(0);expect(screen.queryByText("Root",{selector:"p"})).not.toBeInTheDocument();});
 it("shows only the two contextual actions after a node is selected",async()=>{renderEdit();await screen.findByText("Branch A");expect(screen.queryByRole("button",{name:"Add child"})).not.toBeInTheDocument();await selectNode();const actions=screen.getByRole("group",{name:"Actions for Branch A"});expect(within(actions).getAllByRole("button").map(button=>button.textContent)).toEqual(["+Add child","Edit node"]);expect(screen.queryByRole("complementary",{name:"Life node editor"})).not.toBeInTheDocument();});
 it("dismisses node selection and actions on repeat click, outside pointer press, and Escape",async()=>{renderEdit();const card=await screen.findByRole("button",{name:/Branch A/});await selectNode();expect(screen.getByRole("group",{name:"Actions for Branch A"})).toBeInTheDocument();await selectNode();expect(screen.queryByRole("group",{name:"Actions for Branch A"})).not.toBeInTheDocument();expect(card).toHaveAttribute("aria-pressed","false");await selectNode();fireEvent.pointerDown(screen.getByRole("tree",{name:"Full Life tree editor"}));expect(screen.queryByRole("group",{name:"Actions for Branch A"})).not.toBeInTheDocument();expect(card).toHaveAttribute("aria-pressed","false");await selectNode();const add=screen.getByRole("button",{name:"Add child"});add.focus();fireEvent.keyDown(document,{key:"Escape"});expect(screen.queryByRole("group",{name:"Actions for Branch A"})).not.toBeInTheDocument();expect(card).toHaveAttribute("aria-pressed","false");await waitFor(()=>expect(document.querySelector(`[data-life-edit-id="${a.id}"]`)).toHaveFocus());});
 it("moves leaf actions above dense siblings and closes them after an action",async()=>{renderEdit();await selectNode();expect(screen.getByRole("group",{name:"Actions for Branch A"})).toHaveAttribute("data-placement","below");await selectNode(b.id);expect(screen.queryByRole("group",{name:"Actions for Branch A"})).not.toBeInTheDocument();const leafActions=screen.getByRole("group",{name:"Actions for Branch B"});expect(leafActions).toHaveAttribute("data-placement","above");fireEvent.click(within(leafActions).getByRole("button",{name:"Edit node"}));expect(screen.queryByRole("group",{name:"Actions for Branch B"})).not.toBeInTheDocument();expect(screen.getByRole("complementary",{name:"Life node editor"})).toBeInTheDocument();});
 it("pans the scrollbar-free canvas without treating a node gesture as canvas panning",async()=>{const view=renderEdit();await screen.findByRole("tree");const viewport=view.container.querySelector<HTMLElement>("[data-life-pan-surface]")!;const initialLeft=viewport.scrollLeft;const initialTop=viewport.scrollTop;expect(viewport).toHaveAttribute("tabindex","0");fireEvent.pointerDown(viewport,{button:0,pointerId:7,clientX:220,clientY:190});expect(viewport).toHaveAttribute("data-panning","true");fireEvent.pointerMove(viewport,{pointerId:7,clientX:150,clientY:130});expect(viewport.scrollLeft).toBe(initialLeft+70);expect(viewport.scrollTop).toBe(initialTop+60);fireEvent.pointerUp(viewport,{pointerId:7});expect(viewport).toHaveAttribute("data-panning","false");fireEvent.keyDown(viewport,{key:"ArrowRight"});fireEvent.keyDown(viewport,{key:"ArrowDown",shiftKey:true});expect(viewport.scrollLeft).toBe(initialLeft+150);expect(viewport.scrollTop).toBe(initialTop+240);fireEvent.keyDown(viewport,{key:"Home"});expect(viewport.scrollLeft).toBe(0);expect(viewport.scrollTop).toBe(0);const card=view.container.querySelector<HTMLElement>(`[data-life-edit-id="${a.id}"]`)!;fireEvent.pointerDown(card,{button:0,pointerId:9,clientX:50,clientY:50});expect(viewport).toHaveAttribute("data-panning","false");});
 it("dampens wheel and trackpad scrolling while keeping horizontal wheel navigation",async()=>{const view=renderEdit();await screen.findByRole("tree");const viewport=view.container.querySelector<HTMLElement>("[data-life-pan-surface]")!;const initialLeft=viewport.scrollLeft;const initialTop=viewport.scrollTop;fireEvent.wheel(viewport,{deltaY:120});expect(viewport.scrollTop).toBe(initialTop+42);expect(viewport.scrollLeft).toBe(initialLeft);fireEvent.wheel(viewport,{deltaY:1000,shiftKey:true});expect(viewport.scrollLeft).toBe(initialLeft+42);expect(viewport.scrollTop).toBe(initialTop+42);fireEvent.wheel(viewport,{deltaX:20,deltaY:10});expect(viewport.scrollLeft).toBeCloseTo(initialLeft+49.6);expect(viewport.scrollTop).toBeCloseTo(initialTop+45.8);fireEvent.wheel(viewport,{deltaY:3,deltaMode:1});expect(viewport.scrollTop).toBeCloseTo(initialTop+64.04);});
 it("creates a child through the contextual one-field dialog",async()=>{const {client}=renderEdit();const invalidate=vi.spyOn(client,"invalidateQueries");await selectNode();fireEvent.click(screen.getByRole("button",{name:"Add child"}));const dialog=screen.getByRole("dialog",{name:"Add child to Branch A"});const input=within(dialog).getByLabelText("Child title");expect(input).toHaveAttribute("required");expect(input).toHaveAttribute("maxlength","120");expect(input).toHaveAttribute("inputmode","text");fireEvent.change(input,{target:{value:"New child"}});fireEvent.click(within(dialog).getByRole("button",{name:"Add child"}));await waitFor(()=>expect(api.create).toHaveBeenCalledWith(expect.objectContaining({parent_id:a.id,title:"New child",context:expect.objectContaining({expected_tree_revision:4})})));await waitFor(()=>expect(invalidate).toHaveBeenCalledWith({queryKey:["task-saved-view-projection"]}));expect(invalidate).toHaveBeenCalledWith({queryKey:["task-saved-view-options"]});expect(invalidate).toHaveBeenCalledWith({queryKey:["life-links"]});});
 it("selects a created child only after authoritative geometry contains it",async()=>{const child={...grand,id:"00000000-0000-7000-8000-000000000099",parent_id:a.id,title:"New child"};api.create.mockResolvedValueOnce(result(child));api.projection.mockReset();api.projection.mockResolvedValueOnce(fixture).mockResolvedValue({...fixture,tree_revision:5,nodes:[...fixture.nodes,child]});renderEdit();await selectNode();fireEvent.click(screen.getByRole("button",{name:"Add child"}));const dialog=screen.getByRole("dialog");fireEvent.change(within(dialog).getByLabelText("Child title"),{target:{value:"New child"}});fireEvent.click(within(dialog).getByRole("button",{name:"Add child"}));await screen.findByText("New child");await waitFor(()=>expect(document.querySelector(`[data-life-edit-id="${child.id}"]`)).toHaveAttribute("aria-pressed","true"));expect(screen.getByRole("group",{name:"Actions for New child"})).toBeInTheDocument();});
 it("renames and saves bounded metadata only after Edit node is requested",async()=>{renderEdit();await openNodeEditor();fireEvent.change(screen.getByLabelText("Title"),{target:{value:"Renamed"}});fireEvent.click(screen.getByRole("button",{name:"Save title"}));await waitFor(()=>expect(api.rename).toHaveBeenCalledWith(expect.objectContaining({node_id:a.id,value:"Renamed"})));fireEvent.change(screen.getByLabelText("Short description"),{target:{value:"Updated"}});fireEvent.change(screen.getByLabelText("Local icon"),{target:{value:"life-focus"}});fireEvent.click(screen.getByRole("button",{name:"Save details"}));await waitFor(()=>expect(api.details).toHaveBeenCalledWith(expect.objectContaining({short_description:"Updated",icon_key:"life-focus"})));});
 it("keeps archived nodes outside active geometry and restores them",async()=>{renderEdit();const tree=await screen.findByRole("tree");expect(within(tree).queryByText("Archived")).not.toBeInTheDocument();await openNodeEditor();const section=screen.getByRole("heading",{name:"Archived nodes"}).closest("section")!;fireEvent.click(within(section).getByRole("button",{name:"Restore"}));await waitFor(()=>expect(api.restore).toHaveBeenCalledWith(expect.objectContaining({node_id:archived.id})));});
 it("offers keyboard-equivalent sibling reorder",async()=>{renderEdit();await openNodeEditor();fireEvent.click(screen.getByRole("button",{name:"Move down"}));await waitFor(()=>expect(api.reorder).toHaveBeenCalledWith(expect.objectContaining({node_id:a.id,new_index:1})));});
 it("reparents with one atomic typed command",async()=>{renderEdit();await openNodeEditor();fireEvent.change(screen.getByLabelText("Move into branch"),{target:{value:b.id}});fireEvent.click(screen.getByRole("button",{name:"Move into selected branch"}));await waitFor(()=>expect(api.reparent).toHaveBeenCalledTimes(1));expect(api.reparent).toHaveBeenCalledWith(expect.objectContaining({node_id:a.id,new_parent_id:b.id}));});
 it("removes self and descendants from valid parent choices",async()=>{renderEdit();await openNodeEditor();const options=within(screen.getByLabelText("Move into branch")).getAllByRole("option").map(option=>(option as HTMLOptionElement).value);expect(options).not.toContain(a.id);expect(options).not.toContain(grand.id);expect(options).toContain(b.id);});
 it("archives a subtree and never exposes root archive",async()=>{renderEdit();await openNodeEditor();fireEvent.click(screen.getByRole("button",{name:"Archive subtree"}));await waitFor(()=>expect(api.archive).toHaveBeenCalledWith(expect.objectContaining({node_id:a.id})));await openNodeEditor(root.id);expect(screen.queryByRole("button",{name:"Archive subtree"})).not.toBeInTheDocument();});
 it("undoes only through backend authority",async()=>{renderEdit();await openNodeEditor();fireEvent.click(screen.getByRole("button",{name:"Undo latest tree change"}));await waitFor(()=>expect(api.undo).toHaveBeenCalledWith({undo_token:"undo-4",expected_tree_revision:4}));});
 it("restores Browse focus context through the selected node",async()=>{const onBrowse=vi.fn();renderEdit(onBrowse);await openNodeEditor();fireEvent.click(screen.getByRole("button",{name:"Open in Browse"}));expect(onBrowse).toHaveBeenCalledWith(a.id);});
 it("rolls authoritative geometry back on mutation failure",async()=>{api.reorder.mockRejectedValueOnce(new Error("Revision conflict"));renderEdit();await openNodeEditor();fireEvent.click(screen.getByRole("button",{name:"Move down"}));expect((await screen.findAllByText("Revision conflict")).length).toBeGreaterThan(0);expect(screen.getByText("Branch A")).toBeInTheDocument();});
 it("states that direct node drag and drop is disabled and excludes Narrative Canvas controls",async()=>{renderEdit();await screen.findByText("Branch A");expect(screen.getByText(/Node drag and drop is disabled/)).toBeInTheDocument();expect(screen.queryByText(/Narrative Canvas|React Flow|document editor/i)).not.toBeInTheDocument();});
 it("never exposes a node drag handle or invokes structural mutations from a drag gesture",async()=>{const view=renderEdit();await screen.findByText("Branch A");const card=view.container.querySelector<HTMLElement>(`[data-life-edit-id="${a.id}"]`)!;const target=view.container.querySelector<HTMLElement>(`[data-life-edit-id="${b.id}"]`)!;expect(card).toHaveAttribute("draggable","false");expect(card).not.toHaveAttribute("aria-roledescription");fireEvent.pointerDown(card,{button:0,pointerId:10,clientX:50,clientY:50});fireEvent.pointerMove(target,{pointerId:10,clientX:380,clientY:180});fireEvent.pointerUp(target,{pointerId:10,clientX:380,clientY:180});expect(api.reorder).not.toHaveBeenCalled();expect(api.reparent).not.toHaveBeenCalled();expect(screen.queryByText(/Moving Branch A|Moving Life node/)).not.toBeInTheDocument();});
 it("keeps explicit move controls available",async()=>{renderEdit();await openNodeEditor();expect(screen.getByRole("button",{name:"Move down"})).toBeEnabled();});
 it("lays title-fitted nodes left to right with compact collision-safe clearance",()=>{const layout=buildLifeEditLayout(fixture.nodes);expect(layout.points.get(root.id)!.x).toBeLessThan(layout.points.get(a.id)!.x);expect(layout.points.get(a.id)!.x).toBeLessThan(layout.points.get(grand.id)!.x);expect(layout.points.get(root.id)!.width).toBe(196);expect(Math.abs(layout.points.get(a.id)!.y-layout.points.get(b.id)!.y)).toBeGreaterThanOrEqual(78);expect(Math.abs(layout.points.get(a.id)!.y-layout.points.get(b.id)!.y)).toBeLessThan(110);expect(layout.points.get(a.id)!.x-layout.points.get(root.id)!.x-layout.points.get(root.id)!.width).toBe(44);expect(layout.links[0]!.d).toMatch(/^M 220 .* C .* 264 /);});
 it("expands longer node titles up to a wrapping-safe maximum",()=>{const layout=buildLifeEditLayout([{...root,title:"LIFE FOCUS SYSTEM"},{...a,title:"Academic & Professional Communities"},{...b,title:"A".repeat(120)}]);expect(layout.points.get(a.id)!.width).toBeGreaterThan(layout.points.get(root.id)!.width);expect(layout.points.get(b.id)!.width).toBe(440);expect(layout.points.get(b.id)!.height).toBeGreaterThan(62);});
 it("keeps adjacent maximum-length wrapped titles collision-free",()=>{const layout=buildLifeEditLayout([{...root,title:"LIFE FOCUS SYSTEM"},{...a,title:"W".repeat(120)},{...b,title:"W".repeat(120)}]);const first=layout.points.get(a.id)!;const second=layout.points.get(b.id)!;expect(first.height).toBeGreaterThan(78);expect(Math.abs(first.y-second.y)).toBeGreaterThanOrEqual((first.height+second.height)/2+16);});
 it("keeps every card in the canonical 53-node Life Focus tree collision-free",()=>{
  const structure:Array<[string,Array<[string,string[]]>]>=[
   ["VITALITY",[["BODY",["Sleep & Physical Recovery","Movement & Fitness","Nutrition & Healthcare"]],["MIND",["Emotional Wellbeing","Stress & Coping","Mental Healthcare"]],["REST & PLAY",["Detachment & Downtime","Play & Entertainment","Hobbies & Exploration"]]]],
   ["CAPABILITY & CONTRIBUTION",[["LEARNING",["Formal & Structured Learning","Domain Knowledge","Language & Communication"]],["CRAFT",["Technical Practice","Research & Inquiry","Projects & Portfolio"]],["WORK & CONTRIBUTION",["Career Pathways","Professional Performance","Leadership & Impact"]]]],
   ["RELATIONSHIPS",[["FAMILY & LOVE",["Parents & Family of Origin","Partner & Marriage","Children & Household"]],["FRIENDS & MENTORS",["Close Friends","Peers & Collaborators","Mentors & Mentees"]],["COMMUNITY",["Academic & Professional Communities","Local & Civic Community","Membership & Belonging"]]]],
   ["SECURITY",[["FINANCE",["Cash Flow & Buffer","Investing & Growth","Insurance & Obligations"]],["HOME & ENVIRONMENT",["Housing","Location & Mobility","Living Environment"]],["SAFETY & CONTINUITY",["Personal & Digital Safety","Documents & Administration","Contingency & Recovery"]]]],
  ];
  const nodes:LifeEditNodeView[]=[{...root,title:"LIFE FOCUS SYSTEM",child_count:4}];
  for(const [domainIndex,[domainTitle,sections]] of structure.entries()){
   const domainId=`domain-${domainIndex}`;
   nodes.push({...a,id:domainId,parent_id:root.id,title:domainTitle,sort_key:domainIndex,depth:1,child_count:3,is_leaf:false});
   for(const [sectionIndex,[sectionTitle,leaves]] of sections.entries()){
    const sectionId=`${domainId}-section-${sectionIndex}`;
    nodes.push({...a,id:sectionId,parent_id:domainId,title:sectionTitle,sort_key:sectionIndex,depth:2,child_count:3,is_leaf:false});
    leaves.forEach((title,leafIndex)=>nodes.push({...grand,id:`${sectionId}-leaf-${leafIndex}`,parent_id:sectionId,title,sort_key:leafIndex,depth:3}));
   }
  }
  const layout=buildLifeEditLayout(nodes);
  const cards=[...layout.points.entries()];
  expect(cards).toHaveLength(53);
  expect(layout.width).toBeLessThan(1500);
  expect(layout.height).toBeLessThan(3200);
  for(let leftIndex=0;leftIndex<cards.length;leftIndex++)for(let rightIndex=leftIndex+1;rightIndex<cards.length;rightIndex++){
   const [leftId,left]=cards[leftIndex]!;const [rightId,right]=cards[rightIndex]!;
   const separatedHorizontally=left.x+left.width<=right.x||right.x+right.width<=left.x;
   const separatedVertically=left.y+left.height<=right.y||right.y+right.height<=left.y;
   expect(separatedHorizontally||separatedVertically,`${leftId} overlaps ${rightId}`).toBe(true);
  }
 });
 it("renders a semantic icon for a node while preserving its full accessible title",async()=>{renderEdit();const card=await screen.findByRole("button",{name:/Branch B/});expect(within(card).getByText("🛟")).toBeInTheDocument();expect(card).toHaveTextContent("Branch B");});
 it("has no critical or serious accessibility violations with contextual actions open",async()=>{const {container}=renderEdit();await selectNode();const results=await axe.run(container);expect(results.violations.filter(item=>item.impact==="critical"||item.impact==="serious")).toHaveLength(0);});
 it("builds deterministic d3 geometry for 100 500 and 2000-node fixtures",()=>{for(const size of [100,500,2000]){const nodes:Array<LifeEditNodeView>=[{...root,child_count:size?1:0}];for(let index=0;index<size;index++){nodes.push({...grand,id:`node-${index}`,parent_id:index===0?root.id:`node-${Math.floor((index-1)/3)}`,title:`Node ${index}`,sort_key:index,depth:1,child_count:0});}const started=performance.now();const layout=buildLifeEditLayout(nodes);expect(layout.points.size).toBe(size+1);expect(performance.now()-started).toBeLessThan(1500);}});
});
