import { fireEvent,render,screen,waitFor,within } from "@testing-library/react";
import { QueryClient,QueryClientProvider } from "@tanstack/react-query";
import { beforeEach,describe,expect,it,vi } from "vitest";
import type { LifeEditNodeView } from "../../ipc/generated/LifeEditNodeView";
import type { LifeEditProjection } from "../../ipc/generated/LifeEditProjection";
import { LifeEditWorkspace,buildLifeEditLayout } from "./LifeEditWorkspace";

const api=vi.hoisted(()=>({projection:vi.fn(),create:vi.fn(),rename:vi.fn(),details:vi.fn(),archive:vi.fn(),restore:vi.fn(),reorder:vi.fn(),reparent:vi.fn(),undo:vi.fn()}));
vi.mock("../../ipc/commands",()=>({getLifeEditProjection:api.projection,createLifeNode:api.create,renameLifeNode:api.rename,updateLifeNodeSummary:api.details,archiveLifeNode:api.archive,restoreLifeNode:api.restore,reorderLifeSibling:api.reorder,reparentLifeNode:api.reparent,undoLifeOperation:api.undo}));
const root:LifeEditNodeView={id:"life-root",parent_id:null,title:"Life",short_description:"Root",icon_key:"life-root",theme_variant:"neutral",sort_key:0,depth:0,child_count:2,is_leaf:false,has_document:false,is_pinned:false,revision:0,tags:[]};
const a:LifeEditNodeView={id:"00000000-0000-7000-8000-000000000001",parent_id:"life-root",title:"Branch A",short_description:"A",icon_key:"life-branch",theme_variant:"blue",sort_key:0,depth:1,child_count:1,is_leaf:false,has_document:false,is_pinned:true,revision:0,tags:[]};
const b:LifeEditNodeView={id:"00000000-0000-7000-8000-000000000002",parent_id:"life-root",title:"Branch B",short_description:"B",icon_key:"life-branch",theme_variant:"green",sort_key:1,depth:1,child_count:0,is_leaf:true,has_document:false,is_pinned:false,revision:0,tags:[]};
const grand:LifeEditNodeView={id:"00000000-0000-7000-8000-000000000003",parent_id:a.id,title:"Grandchild",short_description:"G",icon_key:"life-leaf",theme_variant:"neutral",sort_key:0,depth:2,child_count:0,is_leaf:true,has_document:false,is_pinned:false,revision:0,tags:[]};
const archived:LifeEditNodeView={...grand,id:"00000000-0000-7000-8000-000000000004",title:"Archived",revision:1};
const fixture:LifeEditProjection={root_id:"life-root",tree_revision:4,nodes:[root,a,grand,b],archived_nodes:[archived],latest_undo:"undo-4"};
const result=(node=a)=>({node:{id:node.id,title:node.title,short_description:node.short_description,icon_key:node.icon_key,branch_theme_id:node.theme_variant,child_count:node.child_count,is_leaf:node.is_leaf,is_pinned:node.is_pinned,revision:node.revision+1},tree_revision:5,invalidation:["life-edit"],undo_token:"next"});
const renderEdit=(onBrowse=vi.fn())=>{const client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});return {...render(<QueryClientProvider client={client}><LifeEditWorkspace initialNodeId={a.id} onBrowse={onBrowse}/></QueryClientProvider>),client};};

describe("Life Edit workspace",()=>{
 beforeEach(()=>{api.projection.mockResolvedValue(fixture);for(const mock of [api.create,api.rename,api.details,api.archive,api.restore,api.reorder,api.reparent,api.undo])mock.mockResolvedValue(result());});
 it("renders the complete active tree including grandchildren",async()=>{renderEdit();const tree=await screen.findByRole("tree",{name:"Full Life tree editor"});expect(within(tree).getAllByRole("treeitem")).toHaveLength(4);expect(within(tree).getByText("Grandchild")).toBeInTheDocument();});
 it("uses compact cards with branch leaf child and pin metadata",async()=>{renderEdit();await screen.findByText("Branch A");expect(screen.getByText("1 children · Pinned")).toBeInTheDocument();expect(screen.getAllByText("Leaf").length).toBeGreaterThan(0);expect(screen.queryByText("Root",{selector:"p"})).not.toBeInTheDocument();});
 it("creates a child through one typed mutation",async()=>{const {client}=renderEdit();const invalidate=vi.spyOn(client,"invalidateQueries");await screen.findByText("Branch A");fireEvent.change(screen.getByLabelText("New child title"),{target:{value:"New child"}});fireEvent.click(screen.getByRole("button",{name:"Create child"}));await waitFor(()=>expect(api.create).toHaveBeenCalledWith(expect.objectContaining({parent_id:a.id,title:"New child",context:expect.objectContaining({expected_tree_revision:4})})));await waitFor(()=>expect(invalidate).toHaveBeenCalledWith({queryKey:["task-saved-view-projection"]}));expect(invalidate).toHaveBeenCalledWith({queryKey:["task-saved-view-options"]});expect(invalidate).toHaveBeenCalledWith({queryKey:["life-links"]});});
 it("renames and saves bounded metadata explicitly",async()=>{renderEdit();await screen.findByText("Branch A");fireEvent.change(screen.getByLabelText("Title"),{target:{value:"Renamed"}});fireEvent.click(screen.getByRole("button",{name:"Save title"}));await waitFor(()=>expect(api.rename).toHaveBeenCalledWith(expect.objectContaining({node_id:a.id,value:"Renamed"})));fireEvent.change(screen.getByLabelText("Short description"),{target:{value:"Updated"}});fireEvent.change(screen.getByLabelText("Local icon"),{target:{value:"life-focus"}});fireEvent.click(screen.getByRole("button",{name:"Save details"}));await waitFor(()=>expect(api.details).toHaveBeenCalledWith(expect.objectContaining({short_description:"Updated",icon_key:"life-focus"})));});
 it("keeps archived nodes outside active geometry and restores them",async()=>{renderEdit();const tree=await screen.findByRole("tree");expect(within(tree).queryByText("Archived")).not.toBeInTheDocument();const section=screen.getByRole("heading",{name:"Archived nodes"}).closest("section")!;fireEvent.click(within(section).getByRole("button",{name:"Restore"}));await waitFor(()=>expect(api.restore).toHaveBeenCalledWith(expect.objectContaining({node_id:archived.id})));});
 it("offers keyboard-equivalent sibling reorder",async()=>{renderEdit();await screen.findByText("Branch A");fireEvent.click(screen.getByRole("button",{name:"Move down"}));await waitFor(()=>expect(api.reorder).toHaveBeenCalledWith(expect.objectContaining({node_id:a.id,new_index:1})));});
 it("reparents with one atomic typed command",async()=>{renderEdit();await screen.findByText("Branch A");fireEvent.change(screen.getByLabelText("Move into branch"),{target:{value:b.id}});fireEvent.click(screen.getByRole("button",{name:"Move into selected branch"}));await waitFor(()=>expect(api.reparent).toHaveBeenCalledTimes(1));expect(api.reparent).toHaveBeenCalledWith(expect.objectContaining({node_id:a.id,new_parent_id:b.id}));});
 it("removes self and descendants from valid parent choices",async()=>{renderEdit();await screen.findByText("Branch A");const options=within(screen.getByLabelText("Move into branch")).getAllByRole("option").map(option=>(option as HTMLOptionElement).value);expect(options).not.toContain(a.id);expect(options).not.toContain(grand.id);expect(options).toContain(b.id);});
 it("archives a subtree and never exposes root archive",async()=>{const view=renderEdit();await screen.findByText("Branch A");fireEvent.click(screen.getByRole("button",{name:"Archive subtree"}));await waitFor(()=>expect(api.archive).toHaveBeenCalledWith(expect.objectContaining({node_id:a.id})));fireEvent.click(view.container.querySelector<HTMLElement>('[data-life-edit-id="life-root"]')!);expect(screen.queryByRole("button",{name:"Archive subtree"})).not.toBeInTheDocument();});
 it("undoes only through backend authority",async()=>{renderEdit();await screen.findByText("Branch A");fireEvent.click(screen.getByRole("button",{name:"Undo latest tree change"}));await waitFor(()=>expect(api.undo).toHaveBeenCalledWith({undo_token:"undo-4",expected_tree_revision:4}));});
 it("restores Browse focus context through the selected node",async()=>{const onBrowse=vi.fn();renderEdit(onBrowse);await screen.findByText("Branch A");fireEvent.click(screen.getByRole("button",{name:"Open in Browse"}));expect(onBrowse).toHaveBeenCalledWith(a.id);});
 it("rolls authoritative geometry back on mutation failure",async()=>{api.reorder.mockRejectedValueOnce(new Error("Revision conflict"));renderEdit();await screen.findByText("Branch A");fireEvent.click(screen.getByRole("button",{name:"Move down"}));expect((await screen.findAllByText("Revision conflict")).length).toBeGreaterThan(0);expect(screen.getByText("Branch A")).toBeInTheDocument();});
 it("includes dnd instructions and excludes Narrative Canvas controls",async()=>{renderEdit();await screen.findByText("Branch A");expect(screen.getByText(/Use drag and drop/)).toBeInTheDocument();expect(screen.queryByText(/Narrative Canvas|React Flow|document editor/i)).not.toBeInTheDocument();});
 it("starts keyboard drag with Enter and renders the DragOverlay",async()=>{const view=renderEdit();await screen.findByText("Branch A");const card=view.container.querySelector<HTMLElement>(`[data-life-edit-id="${a.id}"]`)!;card.focus();fireEvent.keyDown(card,{code:"Enter",key:"Enter"});expect(await screen.findByText("Moving Branch A")).toBeInTheDocument();expect(screen.getAllByText(/Moving Life node/).length).toBeGreaterThan(0);fireEvent.keyDown(card,{code:"Escape",key:"Escape"});});
 it("exposes a deterministic reduced-motion state without removing controls",async()=>{const view=renderEdit();await screen.findByText("Branch A");expect(view.container.querySelector("[data-reduced-motion]")).toHaveAttribute("data-reduced-motion");expect(screen.getByRole("button",{name:"Move down"})).toBeEnabled();});
 it("builds deterministic d3 geometry for 100 500 and 2000-node fixtures",()=>{for(const size of [100,500,2000]){const nodes:Array<LifeEditNodeView>=[{...root,child_count:size?1:0}];for(let index=0;index<size;index++){nodes.push({...grand,id:`node-${index}`,parent_id:index===0?root.id:`node-${Math.floor((index-1)/3)}`,title:`Node ${index}`,sort_key:index,depth:1,child_count:0});}const started=performance.now();const layout=buildLifeEditLayout(nodes);expect(layout.points.size).toBe(size+1);expect(performance.now()-started).toBeLessThan(1500);}});
});
