import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { AnalyticsScreen } from "./AnalyticsScreen";
import { CategoryGoals } from "./CategoryGoals";
import * as commands from "../../ipc/commands";

vi.mock("../../ipc/commands",()=>({getAnalyticsProjection:vi.fn(),listTaskCategories:vi.fn(),updateCategoryGoals:vi.fn()}));
const projection={period_kind:"week" as const,period_start:"2026-07-27",period_end:"2026-08-02",is_complete:true,algorithm_version:1,computed_at:"1",source_revision:"4",scheduled_minutes:180,task_count:3,evaluated_count:2,missed_count:1,categories:[{category_id:"general",category_name:"General",category_icon_key:"category-general",category_color_key:"blue",scheduled_minutes:180,weekly_minimum_minutes:120,weekly_target_minutes:150,minimum_attained_minutes:120,target_attained_minutes:150,minimum_shortfall_minutes:0,target_shortfall_minutes:0,minimum_overage_minutes:60,target_overage_minutes:30,eligible_week_count:1,minimum_week_count:1,target_week_count:1},{category_id:"open",category_name:"Open",category_icon_key:"category-general",category_color_key:"blue",scheduled_minutes:30,weekly_minimum_minutes:null,weekly_target_minutes:null,minimum_attained_minutes:0,target_attained_minutes:0,minimum_shortfall_minutes:0,target_shortfall_minutes:0,minimum_overage_minutes:30,target_overage_minutes:30,eligible_week_count:0,minimum_week_count:0,target_week_count:0}],completion_distribution:[{state_id:"completion-met",label:"Met expectation",visual_token:"met",count:2}],streaks:[{category_id:"general",threshold_kind:"minimum",current_length:2,longest_length:4,current_start:"2026-07-20",longest_start:"2026-06-01",last_break_week:"2026-07-13"},{category_id:"general",threshold_kind:"target",current_length:1,longest_length:3,current_start:"2026-07-27",longest_start:"2026-06-08",last_break_week:"2026-07-20"}]};
const renderWithClient=(node:React.ReactNode)=>render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}})}>{node}</QueryClientProvider>);
describe("objective Analytics",()=>{beforeEach(()=>{vi.mocked(commands.getAnalyticsProjection).mockResolvedValue(projection);vi.mocked(commands.listTaskCategories).mockResolvedValue([])});
 it("replaces the placeholder with fixed accessible period tabs",async()=>{renderWithClient(<AnalyticsScreen/>);expect(await screen.findByRole("heading",{name:"Analytics"})).toBeInTheDocument();expect(screen.getAllByRole("tab").map(x=>x.textContent)).toEqual(["Week","Month","Year"]);});
 it("navigates adjacent and current periods through bounded queries",async()=>{renderWithClient(<AnalyticsScreen/>);await screen.findByText("Scheduled time");fireEvent.click(screen.getByRole("button",{name:"Previous period"}));fireEvent.click(screen.getByRole("tab",{name:"Month"}));fireEvent.click(screen.getByRole("button",{name:"Next period"}));fireEvent.click(screen.getByRole("button",{name:"Current period"}));await waitFor(()=>expect(vi.mocked(commands.getAnalyticsProjection).mock.calls.length).toBeGreaterThanOrEqual(4));});
 it("uses Scheduled time as the primary metric and never renders a score or AI insight",async()=>{renderWithClient(<AnalyticsScreen/>);expect(await screen.findByText("3h 0m")).toBeInTheDocument();expect(screen.getByText("Scheduled time")).toBeInTheDocument();expect(screen.queryByText(/score|AI insight/i)).not.toBeInTheDocument();});
 it("renders configured attainment and a clear unconfigured state",async()=>{renderWithClient(<AnalyticsScreen/>);expect(await screen.findByText("1h 0m over minimum")).toBeInTheDocument();expect(screen.getByText("0h 30m over target")).toBeInTheDocument();expect(screen.getByText("Weekly minimum and target not configured.")).toBeInTheDocument();});
 it("renders objective streaks and visual plus table distribution equivalents",async()=>{renderWithClient(<AnalyticsScreen/>);expect(await screen.findByText(/minimum: current 2 weeks; longest 4 weeks/)).toBeInTheDocument();expect(screen.getByRole("table",{name:"Evaluation counts"})).toBeInTheDocument();expect(screen.getByRole("cell",{name:"2"})).toBeInTheDocument();});
 it("shows completed-week attainment for Month and Year",async()=>{renderWithClient(<AnalyticsScreen/>);await screen.findByText("Scheduled time");fireEvent.click(screen.getByRole("tab",{name:"Year"}));expect(await screen.findByText(/1 of 1 completed weeks met minimum/)).toBeInTheDocument();});
 it("keeps loading and error states accessible",async()=>{vi.mocked(commands.getAnalyticsProjection).mockRejectedValueOnce(new Error("failure"));renderWithClient(<AnalyticsScreen/>);expect(await screen.findByRole("alert")).toHaveTextContent("Unable to load objective Analytics.");});
});

describe("category scheduled-time goals",()=>{beforeEach(()=>{vi.mocked(commands.listTaskCategories).mockResolvedValue([{id:"general",name:"General",icon_key:"category-general",color_key:"blue",weekly_minimum_minutes:60,weekly_target_minutes:120,goal_revision:2}]);vi.mocked(commands.updateCategoryGoals).mockResolvedValue({id:"general",name:"General",icon_key:"category-general",color_key:"blue",weekly_minimum_minutes:120,weekly_target_minutes:180,goal_revision:3});});
 it("loads duration controls and saves typed minutes",async()=>{renderWithClient(<CategoryGoals/>);expect(await screen.findByRole("heading",{name:"General"})).toBeInTheDocument();fireEvent.change(screen.getByLabelText("Weekly minimum hours"),{target:{value:"2"}});fireEvent.change(screen.getByLabelText("Weekly target hours"),{target:{value:"3"}});fireEvent.click(screen.getByRole("button",{name:"Save goals"}));await waitFor(()=>expect(commands.updateCategoryGoals).toHaveBeenCalledWith(expect.objectContaining({weekly_minimum_minutes:120,weekly_target_minutes:180,expected_revision:2})));});
 it("validates minimum before target without sending",async()=>{renderWithClient(<CategoryGoals/>);await screen.findByRole("heading",{name:"General"});fireEvent.change(screen.getByLabelText("Weekly minimum hours"),{target:{value:"3"}});fireEvent.change(screen.getByLabelText("Weekly target hours"),{target:{value:"1"}});fireEvent.click(screen.getByRole("button",{name:"Save goals"}));expect(await screen.findByRole("alert")).toHaveTextContent("Minimum must not exceed target");expect(commands.updateCategoryGoals).not.toHaveBeenCalled();});
 it("can explicitly clear configured goals",async()=>{renderWithClient(<CategoryGoals/>);await screen.findByRole("heading",{name:"General"});fireEvent.click(screen.getByRole("checkbox",{name:"Configure scheduled-time goals"}));fireEvent.click(screen.getByRole("button",{name:"Save goals"}));await waitFor(()=>expect(commands.updateCategoryGoals).toHaveBeenCalledWith(expect.objectContaining({weekly_minimum_minutes:null,weekly_target_minutes:null})));});
});
