import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect, useState } from "react";
import { listTaskCategories, updateCategoryGoals } from "../../ipc/commands";
import type { TaskCategoryView } from "../../ipc/generated/TaskCategoryView";
import { localToday } from "../calendar/date";

const operation=()=>crypto.randomUUID();
function DurationFields({name,value,onChange}:{name:string;value:number;onChange:(value:number)=>void}){return <fieldset><legend>{name}</legend><label>Hours <input aria-label={`${name} hours`} type="number" min="0" max="168" value={Math.floor(value/60)} onChange={e=>onChange(Number(e.target.value)*60+value%60)}/></label><label>Minutes <input aria-label={`${name} minutes`} type="number" min="0" max="59" value={value%60} onChange={e=>onChange(Math.floor(value/60)*60+Number(e.target.value))}/></label></fieldset>}
function GoalEditor({category}:{category:TaskCategoryView}){const client=useQueryClient(),[configured,setConfigured]=useState(category.weekly_minimum_minutes!==null),[minimum,setMinimum]=useState(category.weekly_minimum_minutes??0),[target,setTarget]=useState(category.weekly_target_minutes??0),[error,setError]=useState("");useEffect(()=>{setConfigured(category.weekly_minimum_minutes!==null);setMinimum(category.weekly_minimum_minutes??0);setTarget(category.weekly_target_minutes??0)},[category]);const mutation=useMutation({mutationFn:()=>updateCategoryGoals({category_id:category.id,weekly_minimum_minutes:configured?minimum:null,weekly_target_minutes:configured?target:null,expected_revision:category.goal_revision,operation_id:operation(),observed_local_date:localToday()}),onSuccess:async()=>{setError("");await Promise.all([client.invalidateQueries({queryKey:["task-categories"]}),client.invalidateQueries({queryKey:["analytics"]})])},onError:value=>setError(value instanceof Error?value.message:"Unable to save category goals.")});return <form onSubmit={event=>{event.preventDefault();if(configured&&(minimum<0||target<minimum||target>10080)){setError("Minimum must not exceed target, and target must fit within one week.");return}mutation.mutate()}}><h3>{category.name}</h3><label><input type="checkbox" checked={configured} onChange={event=>setConfigured(event.target.checked)}/> Configure scheduled-time goals</label>{configured&&<><DurationFields name="Weekly minimum" value={minimum} onChange={setMinimum}/><DurationFields name="Weekly target" value={target} onChange={setTarget}/></>}{error&&<p role="alert">{error}</p>}<button disabled={mutation.isPending}>{mutation.isPending?"Saving…":"Save goals"}</button></form>}
export function CategoryGoals(){const query=useQuery({queryKey:["task-categories"],queryFn:listTaskCategories});return <section aria-labelledby="category-goals-heading"><h2 id="category-goals-heading">Category goals</h2><p>Configure weekly scheduled-time minimums and targets. Changes apply from the current local week.</p>{query.isLoading&&<p aria-live="polite">Loading category goals…</p>}{query.isError&&<p role="alert">Unable to load category goals.</p>}{query.data?.map(category=><GoalEditor key={`${category.id}-${category.goal_revision}`} category={category}/>)}</section>}
