import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect, useState } from "react";
import { listTaskCategories, updateCategoryGoals } from "../../ipc/commands";
import type { TaskCategoryView } from "../../ipc/generated/TaskCategoryView";
import { localToday } from "../calendar/date";
import * as styles from "./CategoryGoals.css";
import { LoadingRow } from "../../design-system/primitives/States";

const operation=()=>crypto.randomUUID();
function DurationFields({name,value,onChange}:{name:string;value:number;onChange:(value:number)=>void}){
  // Hours and minutes are two field units inside one bounded group; their separation is the
  // group's gap, never the whitespace that used to sit between two inline labels.
  return <fieldset className={styles.duration}><legend className={styles.legend}>{name}</legend>
    <label className={styles.unit}>Hours<input className={styles.number} aria-label={`${name} hours`} type="number" min="0" max="168" value={Math.floor(value/60)} onChange={e=>onChange(Number(e.target.value)*60+value%60)}/></label>
    <label className={styles.unit}>Minutes<input className={styles.number} aria-label={`${name} minutes`} type="number" min="0" max="59" value={value%60} onChange={e=>onChange(Math.floor(value/60)*60+Number(e.target.value))}/></label>
  </fieldset>;
}
function GoalEditor({category}:{category:TaskCategoryView}){const client=useQueryClient(),[configured,setConfigured]=useState(category.weekly_minimum_minutes!==null),[minimum,setMinimum]=useState(category.weekly_minimum_minutes??0),[target,setTarget]=useState(category.weekly_target_minutes??0),[error,setError]=useState("");useEffect(()=>{setConfigured(category.weekly_minimum_minutes!==null);setMinimum(category.weekly_minimum_minutes??0);setTarget(category.weekly_target_minutes??0)},[category]);const mutation=useMutation({mutationFn:()=>updateCategoryGoals({category_id:category.id,weekly_minimum_minutes:configured?minimum:null,weekly_target_minutes:configured?target:null,expected_revision:category.goal_revision,operation_id:operation(),observed_local_date:localToday()}),onSuccess:async()=>{setError("");await Promise.all([client.invalidateQueries({queryKey:["task-categories"]}),client.invalidateQueries({queryKey:["analytics"]})])},onError:value=>setError(value instanceof Error?value.message:"Unable to save category goals.")});return <form className={styles.editor} onSubmit={event=>{event.preventDefault();if(configured&&(minimum<0||target<minimum||target>10080)){setError("Minimum must not exceed target, and target must fit within one week.");return}mutation.mutate()}}><h3 className={styles.heading}>{category.name}</h3><label className={styles.toggle}><input type="checkbox" checked={configured} onChange={event=>setConfigured(event.target.checked)}/>Configure scheduled-time goals</label>{configured&&<><DurationFields name="Weekly minimum" value={minimum} onChange={setMinimum}/><DurationFields name="Weekly target" value={target} onChange={setTarget}/></>}{error&&<p role="alert">{error}</p>}<button className={styles.save} disabled={mutation.isPending}>{mutation.isPending?"Saving…":"Save goals"}</button></form>}
export function CategoryGoals(){const query=useQuery({queryKey:["task-categories"],queryFn:listTaskCategories});return <section className={styles.root} aria-labelledby="category-goals-heading"><h2 id="category-goals-heading">Category goals</h2><p>Configure weekly scheduled-time minimums and targets. Changes apply from the current local week.</p>{query.isLoading&&<LoadingRow label="Loading category goals…" />}{query.isError&&<p role="alert">Unable to load category goals.</p>}<div className={styles.list}>{query.data?.map(category=><GoalEditor key={`${category.id}-${category.goal_revision}`} category={category}/>)}</div></section>}
