import { globalStyle, style } from "@vanilla-extract/css";
import { space } from "../../../app/layout/tokens.css";
import { field as sharedField, splitWorkspace } from "../../../app/layout/layout.css";
import { button, compact, iconButton } from "../../../design-system/primitives/controls.css";
import { text } from "../../../design-system/visual/typography.css";

export const shell = style([splitWorkspace, { vars: { "--lw-split-columns": "minmax(190px, 260px) minmax(0, 1fr)" } }]);
export const manager = style({ display: "flex", flexDirection: "column", gap: space.x3, minInlineSize: 0, paddingInlineEnd: space.group, borderInlineEnd: "1px solid var(--border-subtle)", '@container': { '(max-width: 899px)': { paddingInlineEnd: 0, paddingBlockEnd: space.group, borderInlineEnd: 0, borderBlockEnd: "1px solid var(--border-subtle)" } } });
export const createView = button.primary;
export const viewList = style({ listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: space.x1 });
export const viewLine = style({ display: "grid", gridTemplateColumns: "minmax(0, 1fr)", gap: space.x2, alignItems: "center", padding: space.x1, borderRadius: "var(--radius-control)" });
export const viewSelect = style([button.ghost, { inlineSize: "100%", minInlineSize: 0, justifyContent: "flex-start", overflowWrap: "anywhere", whiteSpace: "normal", textAlign: "left", selectors: { "&[aria-pressed=true]": { backgroundColor: "#FFFFFF", color: "var(--accent)", borderColor: "var(--accent)", boxShadow: "inset 2px 0 0 var(--accent)" } } }]);
export const actions = style({ display: "flex", flexWrap: "wrap", alignItems: "center", justifyContent: "flex-end", gap: space.x1 });
export const iconControl = style([iconButton, button.ghost, compact]);
globalStyle(`${iconControl} svg`, { inlineSize: 16, blockSize: 16 });
export const moveUpIcon = style({ transform: "rotate(90deg)" });
export const moveDownIcon = style({ transform: "rotate(-90deg)" });
export const rowControl = style([button.ghost, compact]);
export const results = style({ minWidth: 0, display: "flex", flexDirection: "column", gap: space.group });
globalStyle(`${manager} > h2, ${results} > h2`, { ...text.sectionTitle, margin: 0 });
export const notice = style({ padding: space.x3, border: "1px solid var(--border-subtle)", borderInlineStart: "3px solid var(--accent)", borderRadius: "var(--radius-control)", backgroundColor: "#FFFFFF", backgroundImage: "var(--paint-grain-fine)" });
export const editorForm = style({ display: "flex", flexDirection: "column", gap: space.group, minInlineSize: 0 });
export const editorBody = style({ display: "flex", flexDirection: "column", gap: space.group, minInlineSize: 0 });
export const field = sharedField;
export const fieldRow = style({ display: "grid", gridTemplateColumns: "repeat(3,minmax(0,1fr))", gap: space.field, '@container': { '(max-width: 560px)': { gridTemplateColumns: "minmax(0,1fr)" } } });
globalStyle(`${editorBody} input, ${editorBody} select`, { inlineSize: "100%", minInlineSize: 0, boxSizing: "border-box" });
export const filterSection = style({ display: "flex", flexDirection: "column", gap: space.x3, minInlineSize: 0 });
globalStyle(`${filterSection} > h3`, { ...text.sectionTitle, margin: 0 });
export const clause = style({ border: "1px solid var(--border-subtle)", borderRadius: "var(--radius-control)", backgroundColor: "#FFFFFF", backgroundImage: "var(--paint-grain-fine)", padding: space.x3, display: "flex", flexDirection: "column", gap: space.x2, minInlineSize: 0 });
export const removeClause = style([button.destructive, compact, { alignSelf: "flex-start" }]);
export const multi = style({ minHeight: 110, width: "100%" });
export const checkboxRow = style({ display: "flex", flexWrap: "wrap", gap: space.x3 });
globalStyle(`${checkboxRow} > label`, { display: "inline-flex", alignItems: "center", gap: space.x1 });
export const addFilter = style({ display: "grid", gridTemplateColumns: "minmax(0,1fr) auto", alignItems: "end", gap: space.x2, minInlineSize: 0 });
export const addFilterControl = style([button.secondary, compact]);
export const modalError = style({ ...text.compactBody, padding: space.x3, border: "1px solid var(--danger)", borderRadius: "var(--radius-control)", backgroundColor: "#FFFFFF", backgroundImage: "var(--paint-grain-fine)", color: "var(--danger)" });
export const modalCancel = button.secondary;
export const modalSave = button.primary;
export const resultList = style({ listStyle: "none", padding: 0, margin: 0 });
export const resultRow = style({ display: "grid", gridTemplateColumns: "minmax(110px, 150px) minmax(0, 1fr) auto", gap: 14, alignItems: "start", padding: `${space.x3} 0`, selectors: { "&:not(:last-child)": { borderBottom: "1px solid var(--border-subtle)" } }, '@media': { '(max-width: 640px)': { gridTemplateColumns: "1fr" } } });
globalStyle(`${resultRow} > time`, { ...text.numeric, color: "var(--text-muted)" });
globalStyle(`${resultRow} > div`, { display: "flex", flexDirection: "column", gap: space.control, minInlineSize: 0 });
globalStyle(`${resultRow} > div > strong`, { ...text.row, fontWeight: 600 });
globalStyle(`${resultRow} > div > p`, { margin: 0, color: "var(--text-muted)" });
export const metadata = style({ ...text.metadata, display: "flex", flexWrap: "wrap", alignItems: "center", gap: space.control, color: "var(--text-muted)" });
export const resultLink = style([button.ghost, compact, { color: "var(--accent)", minBlockSize: 0, maxInlineSize: "100%", justifyContent: "flex-start", overflowWrap: "anywhere", whiteSpace: "normal", textAlign: "left" }]);
export const resultOpen = style([button.secondary, compact]);
