import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { TodayScreen, localToday } from "./TodayScreen";

const oneOff={kind:"one_off",id:"one",occurrence_id:null,series_id:null,original_local_date:null,local_date:localToday(),start_minute:487,end_minute:833,title:"Focus",description:"Deep work",category_id:"general",category_name:"General",category_icon_key:"category-general",category_color_key:"blue",priority:"high",is_override:false};
const recurring={...oneOff,kind:"recurring",id:"series:2026-08-02",occurrence_id:"series:2026-08-02",series_id:"series",original_local_date:"2026-08-02",title:"Weekly review"};
const commands=vi.hoisted(()=>({listTodayItems:vi.fn(),listTaskCategories:vi.fn(),createTask:vi.fn(),updateTask:vi.fn(),deleteTask:vi.fn(),createRecurringTask:vi.fn(),updateRecurringOccurrence:vi.fn()}));
vi.mock("../../../ipc/commands",()=>commands);
const renderToday=()=>render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}})}><TodayScreen/></QueryClientProvider>);

describe("Today recurrence contract",()=>{
 beforeEach(()=>{commands.listTodayItems.mockResolvedValue([oneOff]);commands.listTaskCategories.mockResolvedValue([{id:"general",name:"General",icon_key:"category-general",color_key:"blue"}]);commands.createTask.mockResolvedValue(oneOff);commands.createRecurringTask.mockResolvedValue("series");commands.updateRecurringOccurrence.mockResolvedValue(undefined);commands.deleteTask.mockResolvedValue(undefined);});
 it("renders all timeline periods and keeps recurrence off by default",async()=>{renderToday();await screen.findByText("Focus");for(const name of ["Morning","Afternoon","Evening"])expect(screen.getByRole("heading",{name:new RegExp(name)})).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"Create task"}));expect(screen.getByLabelText("Repeat task")).not.toBeChecked();expect(screen.queryByText("Reminder")).not.toBeInTheDocument();});
 it("sends interval weekdays and count chosen by the user",async()=>{renderToday();await screen.findByText("Focus");fireEvent.click(screen.getByRole("button",{name:"Create task"}));fireEvent.change(screen.getByLabelText("Title"),{target:{value:"Standup"}});fireEvent.click(screen.getByLabelText("Repeat task"));fireEvent.change(screen.getByLabelText("Frequency"),{target:{value:"weekly"}});fireEvent.change(screen.getByLabelText("Recurrence interval"),{target:{value:"2"}});fireEvent.click(screen.getByLabelText("Tue"));fireEvent.click(screen.getByLabelText("count"));fireEvent.change(screen.getByLabelText("Occurrence count"),{target:{value:"7"}});expect(screen.getByRole("list",{name:"Recurrence preview"}).children.length).toBeGreaterThan(0);fireEvent.click(screen.getByRole("button",{name:"Save"}));await waitFor(()=>expect(commands.createRecurringTask).toHaveBeenCalledWith(expect.objectContaining({frequency:"weekly",interval:2,weekdays:[1],count:7,until:null})));});
 it("retains typed recurring identity and exposes all edit scopes",async()=>{commands.listTodayItems.mockResolvedValue([recurring]);renderToday();const row=await screen.findByRole("listitem");expect(screen.getByLabelText("Recurring task")).toBeInTheDocument();fireEvent.doubleClick(row);for(const label of ["Only this occurrence","This and future occurrences","Entire series"])expect(screen.getByLabelText(label)).toBeInTheDocument();fireEvent.click(screen.getByLabelText("This and future occurrences"));fireEvent.click(screen.getByRole("button",{name:"Save"}));await waitFor(()=>expect(commands.updateRecurringOccurrence).toHaveBeenCalledWith(expect.objectContaining({series_id:"series",original_local_date:"2026-08-02",scope:"this_and_future",cancelled:false})));});
 it("submits each recurring edit scope with stable typed identity",async()=>{commands.listTodayItems.mockResolvedValue([recurring]);for(const [label,scope] of [["Only this occurrence","only_this_occurrence"],["This and future occurrences","this_and_future"],["Entire series","entire_series"]] as const){const view=renderToday();fireEvent.doubleClick(await screen.findByRole("listitem"));fireEvent.click(screen.getByLabelText(label));fireEvent.click(screen.getByRole("button",{name:"Save"}));await waitFor(()=>expect(commands.updateRecurringOccurrence).toHaveBeenLastCalledWith(expect.objectContaining({series_id:"series",original_local_date:"2026-08-02",scope,cancelled:false})));view.unmount();}});
 it("moves only this occurrence with its original identity intact",async()=>{commands.listTodayItems.mockResolvedValue([recurring]);renderToday();fireEvent.doubleClick(await screen.findByRole("listitem"));fireEvent.change(screen.getByLabelText("Date"),{target:{value:"2026-08-03"}});fireEvent.click(screen.getByRole("button",{name:"Save"}));await waitFor(()=>expect(commands.updateRecurringOccurrence).toHaveBeenCalledWith(expect.objectContaining({series_id:"series",original_local_date:"2026-08-02",replacement_local_date:"2026-08-03",scope:"only_this_occurrence"})));});
 it("routes recurring delete through every explicit scope and never one-off delete",async()=>{commands.listTodayItems.mockResolvedValue([recurring]);renderToday();fireEvent.doubleClick(await screen.findByRole("listitem"));for(const [label,scope] of [["Only this occurrence","only_this_occurrence"],["This and future occurrences","this_and_future"],["Entire series","entire_series"]] as const){fireEvent.click(screen.getByLabelText(label));fireEvent.click(screen.getByRole("button",{name:"Delete"}));await waitFor(()=>expect(commands.updateRecurringOccurrence).toHaveBeenLastCalledWith(expect.objectContaining({scope,cancelled:true})));if(scope!=="entire_series"){commands.listTodayItems.mockResolvedValue([recurring]);renderToday();fireEvent.doubleClick((await screen.findAllByRole("listitem")).at(-1)!);}}expect(commands.deleteTask).not.toHaveBeenCalled();});
 it("preserves recurring draft and scope after conflict",async()=>{commands.listTodayItems.mockResolvedValue([recurring]);commands.updateRecurringOccurrence.mockRejectedValueOnce(new Error("Conflict at 08:07"));renderToday();fireEvent.doubleClick(await screen.findByRole("listitem"));fireEvent.change(screen.getByLabelText("Title"),{target:{value:"Changed draft"}});fireEvent.click(screen.getByLabelText("Entire series"));fireEvent.click(screen.getByRole("button",{name:"Save"}));expect(await screen.findByRole("alert")).toHaveTextContent("Conflict");expect(screen.getByLabelText("Title")).toHaveValue("Changed draft");expect(screen.getByLabelText("Entire series")).toBeChecked();});
 it("keeps one-off delete on the one-off command",async()=>{renderToday();fireEvent.doubleClick(await screen.findByRole("listitem"));fireEvent.click(screen.getByRole("button",{name:"Delete"}));await waitFor(()=>expect(commands.deleteTask).toHaveBeenCalledWith("one"));expect(commands.updateRecurringOccurrence).not.toHaveBeenCalled();});
});
