import { useEffect, useMemo, useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { createRecurringTask, createTask, deleteTask, listRecurringOccurrences, listTaskCategories, listTasksForDate, updateRecurringOccurrence, updateTask } from "../../../ipc/commands";
import type { TaskCategoryView } from "../../../ipc/generated/TaskCategoryView";
import type { TaskView } from "../../../ipc/generated/TaskView";
import * as styles from "./TodayScreen.css";

export const localToday = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`; };
export const formatMinute = (n:number) => `${String(Math.floor(n/60)).padStart(2,"0")}:${String(n%60).padStart(2,"0")}`;
const parseMinute = (v:string) => { const p=v.split(":").map(Number); return (p[0]??0)*60+(p[1]??0); };
const periods = [{name:"Morning",start:240,end:720},{name:"Afternoon",start:720,end:1080},{name:"Evening",start:1080,end:1440}];
const minuteOptions = (end=false) => Array.from({length:end?1441-240:1200},(_,i)=>i+240);

function TimeWheel({name,value,onChange,end=false}:{name:string;value:number;onChange:(n:number)=>void;end?:boolean}) {
  const h=Math.floor(value/60), m=value%60;
  return <div role="group" aria-label={`${name} time`} className={styles.wheel}><label>{name}<select aria-label={`${name} hour`} value={h} onChange={e=>onChange(Number(e.target.value)*60+m)}>{Array.from({length:end?21:20},(_,i)=>i+4).map(x=><option key={x} value={x}>{String(x).padStart(2,"0")}</option>)}</select><select aria-label={`${name} minute`} value={m} onChange={e=>onChange(h*60+Number(e.target.value))}>{Array.from({length:60},(_,x)=><option key={x} value={x}>{String(x).padStart(2,"0")}</option>)}</select></label></div>;
}

export function TodayScreen() {
  const date=localToday(); const client=useQueryClient(); const [open,setOpen]=useState(false); const [editing,setEditing]=useState<TaskView|null>(null); const [selected,setSelected]=useState<string|null>(null); const [recurring,setRecurring]=useState(false); const [frequency,setFrequency]=useState("daily"); const [scope,setScope]=useState("only_this_occurrence"); const [draft,setDraft]=useState({title:"",description:"",local_date:date,start_minute:480,end_minute:540,category_id:"general",priority:"medium"}); const [fieldError,setFieldError]=useState(""); const trigger=useRef<HTMLButtonElement>(null); const dialog=useRef<HTMLDivElement>(null);
  const tasks=useQuery({queryKey:["tasks",date],queryFn:()=>listTasksForDate(date)}); const recurringTasks=useQuery({queryKey:["recurring",date],queryFn:()=>listRecurringOccurrences(date)}); const cats=useQuery({queryKey:["task-categories"],queryFn:listTaskCategories});
  const mutation=useMutation<TaskView|string|void>({mutationFn:()=>editing?.id.includes(":")?updateRecurringOccurrence({series_id:editing.id.split(":")[0]!,original_local_date:editing.id.split(":")[1]!,replacement_local_date:draft.local_date,title:draft.title,description:draft.description,category_id:draft.category_id,priority:draft.priority,start_minute:draft.start_minute,end_minute:draft.end_minute,scope:scope as never,cancelled:false}):editing?updateTask({id:editing.id,...draft}):recurring?createRecurringTask({...draft,frequency,interval:1,weekdays:[],until:null,count:null}):createTask(draft),onSuccess:()=>{client.invalidateQueries({queryKey:["tasks"]});client.invalidateQueries({queryKey:["recurring"]});setOpen(false);setEditing(null);trigger.current?.focus();},onError:(e)=>setFieldError(e instanceof Error?e.message:"Unable to save task.")});
  const remove=useMutation({mutationFn:()=>deleteTask(editing!.id),onSuccess:()=>{client.invalidateQueries({queryKey:["tasks"]});client.invalidateQueries({queryKey:["recurring"]});setOpen(false);setEditing(null);trigger.current?.focus();}});
  useEffect(()=>{if(!open)return; const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape"){setOpen(false);setEditing(null);trigger.current?.focus();} if(e.key==="Tab"&&dialog.current){const els=[...dialog.current.querySelectorAll<HTMLElement>("button,input,textarea,select")]; if(els.length&& (e.shiftKey?document.activeElement===els[0]:document.activeElement===els.at(-1))){e.preventDefault();(e.shiftKey?els.at(-1):els[0])?.focus();}}}; document.addEventListener("keydown",onKey); dialog.current?.querySelector<HTMLElement>("input,select,textarea,button")?.focus(); return()=>document.removeEventListener("keydown",onKey);},[open]);
  const projected=useMemo(()=>[...(tasks.data??[]),...(recurringTasks.data??[]).map(r=>({...r,id:r.occurrence_id}))] as TaskView[],[tasks.data,recurringTasks.data]); const groups=useMemo(()=>periods.map(p=>({...p,groups:Object.values(projected.filter(t=>t.start_minute>=p.start&&t.start_minute<p.end).reduce((m,t)=>{const k=`${t.start_minute}-${t.end_minute}`;(m[k]??=[]).push(t);return m;},{} as Record<string,TaskView[]>))})),[projected]);
  const begin=(task?:TaskView)=>{setFieldError("");setRecurring(false);setEditing(task??null);setDraft(task?{title:task.title,description:task.description,local_date:task.local_date,start_minute:task.start_minute,end_minute:task.end_minute,category_id:task.category_id,priority:task.priority}:{title:"",description:"",local_date:date,start_minute:480,end_minute:540,category_id:cats.data?.[0]?.id??"general",priority:"medium"});setOpen(true);};
  return <section aria-labelledby="today-heading" className={styles.root}><div className={styles.header}><div><p className={styles.eyebrow}>Today · {date}</p><h1 id="today-heading" tabIndex={-1}>Today</h1></div><button ref={trigger} className={styles.create} aria-label="Create task" onClick={()=>begin()}>Plan task</button></div>{tasks.isLoading?<p aria-live="polite">Loading tasks…</p>:tasks.isError?<p role="alert">Unable to load tasks.</p>:<div className={styles.timeline} role="list">{groups.map(p=><section key={p.name} aria-labelledby={`${p.name}-heading`}><h2 id={`${p.name}-heading`}>{p.name}<span>{formatMinute(p.start)}–{formatMinute(p.end)}</span></h2>{p.groups.length===0?<p className={styles.empty}>No tasks scheduled.</p>:p.groups.map(group=><div className={styles.group} key={`${group[0]!.start_minute}-${group[0]!.end_minute}`}><div className={styles.time}>{formatMinute(group[0]!.start_minute)}–{formatMinute(group[0]!.end_minute)}</div><div>{group.map(t=><div role="listitem" key={t.id} className={`${styles.row} ${selected===t.id?styles.selected:""}`} tabIndex={0} onClick={()=>setSelected(t.id)} onDoubleClick={()=>begin(t)} onKeyDown={e=>{if(e.key==="Enter")begin(t)}}><div><strong>{t.title}</strong><p>{t.description}</p><span aria-label={`Category General`} className={styles.category}>◉ General</span></div><span aria-label={`Priority ${t.priority}`}>•</span><span aria-label="Assessment unavailable" className={styles.assessment}>—</span></div>)}</div></div>)}</section>)}</div>}
    {open&&<div className={styles.dialog} role="dialog" aria-modal="true" aria-labelledby="task-dialog-heading" ref={dialog}><form onSubmit={e=>{e.preventDefault();if(draft.start_minute>=draft.end_minute){setFieldError("Start time must be before end time.");return;}mutation.mutate();}}><h2 id="task-dialog-heading">{editing?"Edit task":"Create task"}</h2>{fieldError&&<p role="alert" id="task-error">{fieldError}</p>}<label>Title<input aria-invalid={!!fieldError} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Description<textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>Date<input type="date" value={draft.local_date} onChange={e=>setDraft({...draft,local_date:e.target.value})}/></label><TimeWheel name="Start" value={draft.start_minute} onChange={n=>setDraft({...draft,start_minute:n})}/><TimeWheel name="End" value={draft.end_minute} end onChange={n=>setDraft({...draft,end_minute:n})}/><label>Category<select value={draft.category_id} onChange={e=>setDraft({...draft,category_id:e.target.value})}>{(cats.data??[]).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{editing?.id.includes(":")&&<fieldset><legend>Edit scope</legend><label><input type="radio" name="scope" checked={scope==="only_this_occurrence"} onChange={()=>setScope("only_this_occurrence")}/> Only this occurrence</label><label><input type="radio" name="scope" checked={scope==="this_and_future"} onChange={()=>setScope("this_and_future")}/> This and future occurrences</label><label><input type="radio" name="scope" checked={scope==="entire_series"} onChange={()=>setScope("entire_series")}/> Entire series</label></fieldset>}<label>Priority<select value={draft.priority} onChange={e=>setDraft({...draft,priority:e.target.value})}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label>{!editing&&<fieldset><legend>Recurring</legend><label><input type="checkbox" checked={recurring} onChange={e=>setRecurring(e.target.checked)}/> Repeat task</label>{recurring&&<label>Frequency<select value={frequency} onChange={e=>setFrequency(e.target.value)}><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></label>}</fieldset>}<button type="submit" disabled={mutation.isPending}>{mutation.isPending?"Saving…":"Save"}</button><button type="button" onClick={()=>{setOpen(false);setEditing(null);trigger.current?.focus();}}>Cancel</button>{editing&&<button type="button" onClick={()=>remove.mutate()} disabled={remove.isPending}>Delete</button>}</form></div>}</section>;
}






