import { useEffect, useMemo, useState } from "react";
import { createTask, deleteTask, listTaskCategories, listTasksForDate, updateTask } from "../../../ipc/commands";
import type { TaskCategoryView } from "../../../ipc/generated/TaskCategoryView";
import type { TaskView } from "../../../ipc/generated/TaskView";
import * as styles from "./TodayScreen.css";

const today = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`; };
const mins = (v: string) => { const parts=v.split(":").map(Number); return (parts[0]??0)*60+(parts[1]??0); };
const time = (n:number) => `${String(Math.floor(n/60)).padStart(2,"0")}:${String(n%60).padStart(2,"0")}`;
const periods = [{name:"Morning",start:240,end:720},{name:"Afternoon",start:720,end:1080},{name:"Evening",start:1080,end:1440}];

export function TodayScreen() {
  const date = today(); const [tasks,setTasks]=useState<TaskView[]>([]); const [categories,setCategories]=useState<TaskCategoryView[]>([]); const [editing,setEditing]=useState<TaskView|null|undefined>(undefined); const [error,setError]=useState(""); const [loading,setLoading]=useState(true);
  const load=()=>Promise.all([listTasksForDate(date),listTaskCategories()]).then(([t,c])=>{setTasks(t);setCategories(c);}).catch(()=>setError("Unable to load tasks.")).finally(()=>setLoading(false));
  useEffect(()=>{void load();},[]);
  const groups=useMemo(()=>periods.map(p=>({...p,groups:Object.values(tasks.filter(t=>t.start_minute>=p.start&&t.start_minute<p.end).reduce((m,t)=>{const k=`${t.start_minute}-${t.end_minute}`;(m[k]??=[]).push(t);return m;},{} as Record<string,TaskView[]>))})),[tasks]);
  async function save(form: HTMLFormElement){const fd=new FormData(form); const input={title:String(fd.get("title")||""),description:String(fd.get("description")||""),local_date:date,start_minute:mins(String(fd.get("start")||"08:00")),end_minute:mins(String(fd.get("end")||"09:00")),category_id:String(fd.get("category")||categories[0]?.id||"general"),priority:String(fd.get("priority")||"medium")}; try{if(editing) await updateTask({id:editing.id,...input}); else await createTask(input); setEditing(undefined);setError("");await load();}catch(e){setError(e instanceof Error?e.message:"Unable to save task.");}}
  return <section aria-labelledby="today-heading" className={styles.root}><div className={styles.header}><div><p className={styles.eyebrow}>Today · {date}</p><h1 id="today-heading" tabIndex={-1}>Today</h1></div><button className={styles.create} onClick={()=>setEditing(null)}>Create task</button></div>{error&&<div role="alert">{error}</div>}{loading?<p>Loading tasks…</p>:<div className={styles.timeline}>{groups.map(p=><section key={p.name} aria-labelledby={`${p.name}-heading`}><h2 id={`${p.name}-heading`}>{p.name}<span>{time(p.start)}–{time(p.end)}</span></h2>{p.groups.length===0?<p className={styles.empty}>No tasks scheduled.</p>:p.groups.map(group=><div className={styles.group} key={`${group[0]!.start_minute}-${group[0]!.end_minute}`}><div className={styles.time}>{time(group[0]!.start_minute)}–{time(group[0]!.end_minute)}</div><div>{group.map(t=><article key={t.id} className={styles.row} tabIndex={0} onDoubleClick={()=>setEditing(t)} onKeyDown={e=>{if(e.key==="Enter")setEditing(t)}}><div><strong>{t.title}</strong><p>{t.description}</p></div><span aria-label={`Priority ${t.priority}`}>•</span><button aria-label={`Delete ${t.title}`} onClick={async()=>{await deleteTask(t.id);await load();}}>Delete</button></article>)}</div></div>)}</section>)}</div>}{editing!==undefined&&<div role="dialog" aria-modal="true" className={styles.dialog}><form onSubmit={e=>{e.preventDefault();void save(e.currentTarget)}}><h2>{editing?"Edit task":"Create task"}</h2><label>Title<input name="title" defaultValue={editing?.title}/></label><label>Description<textarea name="description" defaultValue={editing?.description}/></label><label>Start<select name="start" defaultValue={time(editing?.start_minute??480)}>{Array.from({length:20},(_,i)=>i+4).flatMap(h=>[0,30].map(m=><option key={`${h}:${m}`} value={`${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}`}>{`${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}`}</option>))}</select></label><label>End<select name="end" defaultValue={time(editing?.end_minute??540)}>{Array.from({length:21},(_,i)=>i+4).flatMap(h=>[0,30].map(m=>h===24&&m?[]:<option key={`${h}:${m}`} value={`${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}`}>{`${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}`}</option>))}</select></label><label>Category<select name="category" defaultValue={editing?.category_id}>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Priority<select name="priority" defaultValue={editing?.priority}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label><button type="submit">Save</button><button type="button" onClick={()=>setEditing(undefined)}>Cancel</button>{editing&&<button type="button" onClick={async()=>{await deleteTask(editing.id);setEditing(undefined);await load();}}>Delete</button>}</form></div>}</section>;
}




