import { style } from "@vanilla-extract/css";
import { focusRing } from "../../design-system/primitives/utilities.css";
import { duration, easing } from "../../design-system/visual/motion.css";
import { text } from "../../design-system/visual/typography.css";
export const anchor=style({position:"relative",display:"grid",placeItems:"center"});
export const trigger=style([focusRing,{width:40,height:40,padding:0,minBlockSize:0,display:"grid",placeItems:"center",border:0,borderRadius:"var(--radius-full)",background:"transparent",cursor:"pointer",selectors:{"&:disabled":{cursor:"not-allowed",opacity:.42}}}]);
export const ring=style({width:22,height:22,border:"2px solid var(--text-muted)",borderRadius:"var(--radius-full)",transition:`background ${duration.check} ${easing.standard}, border-color ${duration.check} ${easing.standard}`,selectors:{[`${trigger}[data-state=none] &`]:{background:"var(--surface)",borderStyle:"double"},[`${trigger}[data-state=below] &`]:{background:"color-mix(in srgb,var(--accent) 30%,transparent)",borderColor:"var(--accent)"},[`${trigger}[data-state=met] &`]:{background:"color-mix(in srgb,var(--accent) 62%,transparent)",borderColor:"var(--accent)"},[`${trigger}[data-state=excellent] &`]:{background:"var(--accent)",borderColor:"var(--accent)",boxShadow:"inset 0 0 0 4px var(--surface)"}}});
export const fan=style({position:"fixed",width:260,height:160,zIndex:"var(--layer-overlay)",pointerEvents:"none",border:"1px solid var(--border-strong)",borderRadius:"var(--radius-floating)",background:"var(--surface-raised)",boxShadow:"var(--elevation-floating)",selectors:{"&[data-compact=true]":{display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:8,width:"calc(100vw - 24px)",maxWidth:240,height:"auto",padding:8}}});
export const option=style({position:"absolute",width:56,height:56,padding:5,border:"1px solid var(--border-subtle)",borderRadius:"var(--radius-full)",background:"var(--surface)",color:"var(--text-primary)",...text.caption,lineHeight:1.08,textAlign:"center",pointerEvents:"auto",transition:`background-color ${duration.popover} ${easing.standard}, border-color ${duration.popover} ${easing.standard}`,selectors:{"&[data-option='0']":{left:4,top:86},"&[data-option='1']":{left:66,top:24},"&[data-option='2']":{left:138,top:24},"&[data-option='3']":{left:200,top:86},[`${fan}[data-orientation=down] &[data-option='0']`]:{top:18},[`${fan}[data-orientation=down] &[data-option='1']`]:{top:80},[`${fan}[data-orientation=down] &[data-option='2']`]:{top:80},[`${fan}[data-orientation=down] &[data-option='3']`]:{top:18},[`${fan}[data-compact=true] &`]:{position:"static",width:"auto",height:48,borderRadius:"var(--radius-control)"},"&:focus-visible":{outline:"2px solid var(--focus-ring)",outlineOffset:2},"&[data-active=true]":{borderColor:"var(--accent)",boxShadow:"inset 0 0 0 1px var(--accent)"},"&[aria-selected=true]":{background:"var(--active-background)",fontWeight:600}}});
